### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ruribev** [UnitySuperEditor/SuperEditor#23]
Hello,

Sometimes it starts to show me a lot of errors on the console as shown in the image:
![image](https://user-images.githubusercontent.com/43749547/131004237-b1042161-414a-4d32-a8c0-2f1be849813f.png)

It goes away after I close and open the Editor. 

All the best,
Rodrigo

**Comment by UnitySuperEditor** [comment]
Hi, Try deleting and re-importing to see if the problem still exists, I've tested the version you're using and it works
Since the Super Editor will be iterated on Unity 2021 or the latest version and will be tested for minimum compatibility with Unity 2019.4.0, it is recommended that you use the official recommended version.

**Comment by ruribev** [comment]
It works great re-importing everything. Cheers!
